Move server-sdk files into packages subdirectory
livekit/server-sdk-js pull request #186
Opened 2024-06-04 11:38 UTC by lukasIO

2024-06-04 15:46 UTC, davidzhao commented
I've enabled merge commits here

2024-06-05 11:10 UTC, theomonnom approved these changes
🚀🚀🚀
let's rename the repo to livekit/node-sdks?

2024-06-05 11:10 UTC, theomonnom commented on .changeset/config.json
> +      "repo": "livekit/node-sdks-temp"
I guess this should be changed?

2024-06-05 14:05 UTC, lukasIO commented
@nbsp I also copied over most of your README proposal for the node real-time SDK, I hope that's alright with you!

2024-06-05 14:19 UTC, nbsp requested changes
this line no longer applies, we removed it in the new PR (which you should also cherry-pick over)

2024-06-05 14:22 UTC, lukasIO commented
I don't see any line associated with your comment, maybe a GH bug? 
I'm assuming you mean the `dispose` call?

2024-06-05 14:33 UTC, nbsp commented
yep

2024-06-05 20:13 UTC, nbsp commented
also, weird nit, it feels odd that our two subfolders are `rtc-node` and `livekit-server-sdk`. i know they're the package names and one of them is under a namespace — but it isn't consistent to have `livekit-` on one but not the other (and the prefix is redundant as well, maybe)

2024-06-05 20:18 UTC, davidzhao commented
can we rename `rtc-node` to `livekit-rtc` ?

2024-06-06 10:44 UTC, nbsp commented on COPYING
out of `/COPYING`, `/NOTICE`, and `/LICENSE`, two of these can go, and COPYING/NOTICE are the same file
i think keeping `COPYING` is the best for GitHub UX without clashing with REUSE

2024-06-06 10:45 UTC, lukasIO commented
> can we rename rtc-node to livekit-rtc ?

sure, I'll make that change and merge the PR. 

We had users (and also Russ) confused in the past as to why repos/folders and the npm package name weren't aligned, so I thought that would be a good shout here. `livekit-rtc` doesn't make a whole lot of sense to me when the package is called `@livekit/rtc-node`.

2024-06-06 10:47 UTC, lukasIO commented on COPYING
can you elaborate on the advantages UX wise? 

Does it hurt to keep `LICENSE` around anyways? It seems like pretty much every bigger repo has that file?

2024-06-06 10:51 UTC, nbsp commented on COPYING
so `NOTICE` isn't picked up by GitHub as being a license file at all, and doesn't give it any special UI
between `LICENSE` and `COPYING` it doesn't really matter per se but i think it's redundant to have the same file once for REUSE and once for GitHub to play nice

2024-06-06 11:00 UTC, lukasIO commented on COPYING
got it, thanks.

2024-06-06 11:54 UTC, merged

2024-06-06 12:02 UTC, nbsp commented
is GH Actions set up to release version packages for rtc-node from this repo as well or not yet?

2024-06-06 14:26 UTC, lukasIO commented
yeah, it's set up to release all packages in scope